version: '2'
services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=hey-here-is-my-secret-mysql-password#qwerty^^^
      - MYSQL_DATABASE=multiconf_db
      - MYSQL_USER=multiconf
      - MYSQL_PASSWORD=hey-here-is-my-secret-mysql-password#qwerty^^^
